# Generated by Django 5.2.9 on 2026-01-08 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0776_add_stream_puppet_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_connected", models.BooleanField(default=False)),
                (
                    "last_connected_time",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "bot",
                    models.OneToOneField(
                        limit_choices_to={"is_bot": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "realm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="zerver.realm"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["realm", "is_connected"],
                        name="zerver_botpresence_realm_connected_idx",
                    )
                ],
            },
        ),
    ]
