# Generated by Django 5.2.9 on 2026-01-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0778_add_user_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="whisper_recipients",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="whisper_recipients",
            field=models.JSONField(default=None, null=True),
        ),
    ]
