# Generated by Django 5.2.9 on 2026-01-09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0779_add_whisper_recipients"),
    ]

    operations = [
        # Add visibility_mode to StreamPuppet
        migrations.AddField(
            model_name="streampuppet",
            name="visibility_mode",
            field=models.CharField(
                choices=[("open", "Open"), ("claimed", "Claimed")],
                default="open",
                max_length=10,
            ),
        ),
        # Add recent_handler_window_hours to StreamPuppet
        migrations.AddField(
            model_name="streampuppet",
            name="recent_handler_window_hours",
            field=models.PositiveIntegerField(default=24),
        ),
        # Create PuppetHandler model
        migrations.CreateModel(
            name="PuppetHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "handler_type",
                    models.CharField(
                        choices=[("claimed", "Claimed"), ("recent", "Recent")],
                        default="recent",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_used", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "handler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handled_puppets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "puppet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handlers",
                        to="zerver.streampuppet",
                    ),
                ),
            ],
            options={
                "unique_together": {("puppet", "handler")},
            },
        ),
    ]
